default:
  image: google/cloud-sdk:slim

variables:
  FUNCTION_NAME: notes-app-backend
  FUNCTIONS_DIR: $CI_PROJECT_DIR/$FUNCTION_NAME
  GCP_REGION: europe-west3
  NOTES_BACKEND_SA: notes-app-sa


# Stages
stages:
  - test
  - deploy

test:
  stage: test
  image: node:hydrogen
  script:
    - cd $FUNCTIONS_DIR
    - yarn --frozen-lockfile
    - yarn lint
    - yarn test


deploy:
  stage: deploy
  before_script:
    - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp_service_account_key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=gcp_service_account_key.json
    - gcloud auth login --cred-file=${GOOGLE_APPLICATION_CREDENTIALS}
    - gcloud config set project $GCP_PROJECT_ID
  script:
    - cd $FUNCTIONS_DIR
    - >
      gcloud functions deploy $FUNCTION_NAME
      --source . --trigger-http --allow-unauthenticated
      --runtime=nodejs20 --gen2 --region=$GCP_REGION
      --entry-point=NotesApp
      --service-account=$NOTES_BACKEND_SA@$GCP_PROJECT_ID.iam.gserviceaccount.com
      --run-service-account=$NOTES_BACKEND_SA@$GCP_PROJECT_ID.iam.gserviceaccount.com
      --set-env-vars NODE_ENV=production,GOOGLE_PROJECT_ID=$GCP_PROJECT_ID
  when: manual
